name: 'build web'

on:
  workflow_dispatch:
  push:
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build WebUI
        run: npm run webpack-prod

      - name: Pack WebUI
        id: pack-webui
        working-directory: dist
        run: |
          GIT_VERSION=$(git describe --tags --always)
          ZIP_FILE="trguing-web-$GIT_VERSION.zip"
          zip -9 -r "$ZIP_FILE" ./* -x 'create*' -x '*.map' -x '*flag-icons*'
          echo "zip_file=$ZIP_FILE" >> "$GITHUB_OUTPUT"

      - name: Upload WebUI artifact
        uses: actions/upload-artifact@v4
        with:
          name: trguing-web
          path: dist/${{ steps.pack-webui.outputs.zip_file }}

      - name: Attach WebUI to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dist/${{ steps.pack-webui.outputs.zip_file }}
